FROM python:3.11-slim-bookworm

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update --fix-missing
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y 

RUN pip install --upgrade pip
COPY ./producer/requirements.txt .
RUN pip install -r requirements.txt

COPY ./producer .
